services:
  selenoid:
    image: aerokube/selenoid:latest-release
    container_name: selenoid
    ports:
      - "4444:4444"
    volumes:
      - ./selenoid/browsers.json:/etc/selenoid/browsers.json:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      -conf /etc/selenoid/browsers.json
      -listen :4444
      -timeout 3m0s
      -limit 4
      -container-network selenoid_net   # <-- ВАЖНО
    networks:
      - selenoid_net

  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    container_name: selenoid-ui
    depends_on:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
    networks:
      - selenoid_net

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sprint_9_tests
    depends_on:
      - selenoid
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - SELENOID_URL=http://selenoid:4444/wd/hub
      - BROWSER=chrome
      - PYTHONPATH=/app/src
    command:
      - sh
      - -c
      - >
        echo 'Waiting for Selenoid at http://selenoid:4444/status';
        until curl -s http://selenoid:4444/status >/dev/null 2>&1; do
          echo 'Selenoid is not ready yet, sleep 2s...';
          sleep 2;
        done;
        echo 'Selenoid is UP, starting tests';
        pytest -v -s src/tests --alluredir=allure_results
    networks:
      - selenoid_net

networks:
  selenoid_net:
    name: selenoid_net
    driver: bridge
